
#autom install a copy of docker 
services:
  - docker

# Do before : -f force -t anynameyouwantforyourimage
before_install: 
  - docker build -t raudez77/end2end-machine-learning -f Dockerfile .

# Run test
# Script contents all script to run
script:
  - docker run raudez77/end2end-machine-learning python test.py -- --coverage

#Deploy into Amazon ElasticBeanstalk
deploy:
  # Use this Saas for deployment
  provider: elasticbeanstalk
  region: us-west-2
  # Application name
  app: "titanic_demo"
  # Enviroment
  env: "Titanicdemo-env"
  # Go Services- S3 - look for yout us-west-2 elastickbeanstalk
  bucket_name: "titanic-bucket-model"
  bucket_path : "docker"

  # Create Acces key in Travis
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
 
  


