# Docker compose for Amazon
version: '3'
services:
  aws_deployment:
    # This fuction force Dockerfile
    build:
      # where are the files coming from (look at the current dir)
      context: .

      # Look for this file
      dockerfile: Dockerfile
    ports:
      - "80:5000"
   