version: '3'
services:
  website:
    # This fuction force Dockerfile.dev
    build:
      # where are the files coming from (look at the current dir)
      context: .

      # Look for this file
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"